Revert "bpo.config.const.branches: add v24.06"
bpo needs to be adjusted first to pass --force-missing-repositories
during the initial build, otherwise it fails with:

  WARNING: opening from cache http://mirror.postmarketos.org/postmarketos/v24.06: No such file or directory
  ERROR: Not continuing due to stale/unavailable repositories.Use --force-missing-repositories to continue.

Revert building v24.06 until this is implemented.

This reverts commit 50581b0f1912d918d98e23d5409bcd32766afa35.