bpo/job_services/sourcehut: install kpartx
pmbootstrap now requires kpartx, so install it.

Fix for:
  ERROR: Can't find all programs required to run pmbootstrap. Please install the following: kpartx