images: v24.12:google-x64cros: set kernel lts
Before the previous patch, this device was using the lts kernel for
v24.12:
https://builds.sr.ht/~postmarketos/job/1519390#task-bpo_setup-46

Configure bpo to use it again so it doesn't fail to build images for
this device with:
RuntimeError: Selected kernel () is not valid for device google-x64cros. Please run 'pmbootstrap init' to select a valid kernel.